WIRINGOP_VERSION = 6b5ccb756a247b73f7cff6630aef942820accbe4
WIRINGOP_SITE = https://github.com/ohmex/WiringPi_2.46.git
WIRINGOP_SITE_METHOD = git
WIRINGOP_LICENSE = LGPL-3.0+
WIRINGOP_LICENSE_FILES = COPYING.LESSER
WIRINGOP_INSTALL_STAGING = YES

ifeq ($(BR2_STATIC_LIBS),y)
WIRINGOP_LIB_BUILD_TARGETS = static
WIRINGOP_LIB_INSTALL_TARGETS = install-static
WIRINGOP_BIN_BUILD_TARGETS = gpio-static
else ifeq ($(BR2_SHARED_LIBS),y)
WIRINGOP_LIB_BUILD_TARGETS = all
WIRINGOP_LIB_INSTALL_TARGETS = install
WIRINGOP_BIN_BUILD_TARGETS = all
else
WIRINGOP_LIB_BUILD_TARGETS = all static
WIRINGOP_LIB_INSTALL_TARGETS = install install-static
WIRINGOP_BIN_BUILD_TARGETS = all
endif

define WIRINGOP_BUILD_CMDS
	$(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D)/wiringPi $(WIRINGOP_LIB_BUILD_TARGETS)
	$(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D)/devLib $(WIRINGOP_LIB_BUILD_TARGETS)
	$(TARGET_MAKE_ENV) $(TARGET_CONFIGURE_OPTS) $(MAKE) -C $(@D)/gpio $(WIRINGOP_BIN_BUILD_TARGETS)
endef

define WIRINGOP_INSTALL_STAGING_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D)/wiringPi $(WIRINGOP_LIB_INSTALL_TARGETS) DESTDIR=$(STAGING_DIR) PREFIX=/usr LDCONFIG=true
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D)/devLib $(WIRINGOP_LIB_INSTALL_TARGETS) DESTDIR=$(STAGING_DIR) PREFIX=/usr LDCONFIG=true
endef

define WIRINGOP_INSTALL_TARGET_CMDS
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D)/wiringPi $(WIRINGOP_LIB_INSTALL_TARGETS) DESTDIR=$(TARGET_DIR) PREFIX=/usr LDCONFIG=true
	$(TARGET_MAKE_ENV) $(MAKE) -C $(@D)/devLib $(WIRINGOP_LIB_INSTALL_TARGETS) DESTDIR=$(TARGET_DIR) PREFIX=/usr LDCONFIG=true
	$(INSTALL) -D -m 0755 $(@D)/gpio/gpio $(TARGET_DIR)/usr/bin/gpio
	$(INSTALL) -D -m 0755 $(@D)/gpio/pintest $(TARGET_DIR)/usr/bin/pintest
endef

$(eval $(generic-package))
