#!/bin/sh

case "$1" in
  start)
        printf "Starting app..."
	    app
        ;;
  stop)
        printf "Stopping app..."
        killall app
        ;;
  restart|reload)
        "$0" stop
        "$0" start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?

